---
- name: clone libkvmi repo
  git:
    repo: 'https://github.com/bitdefender/libkvmi'
    dest: /home/vagrant/libkvmi
    version: master
  become: false

- name: install libkvmi build deps
  package:
    name: "{{ item }}"
  with_items:
    - uuid-dev

- name: bootstrap libkvmi
  command: ./bootstrap
  args:
    chdir: /home/vagrant/libkvmi
  become: false

- name: configure libkvmi
  command: ./configure
  args:
    chdir: /home/vagrant/libkvmi
  become: false

- name: make libkvmi
  command: make
  args:
    chdir: /home/vagrant/libkvmi
  become: false

- name: install libkvmi
  command: make install
  args:
    chdir: /home/vagrant/libkvmi

